name: tier-analysis-app
channels:
  - conda-forge
dependencies:
  - dill
  - numpy
  - pandas
  - python-igraph=0.11.6
  - dask-core
  - distributed
  - cachey
  - certifi
  - openpyxl
  - pyinstaller
  - matplotlib
  - seaborn
